<?php
/**
 * Created by PhpStorm.
 * User: dongyou02
 * Date: 2016/4/28
 * Time: 15:39
 */

namespace Admin\Controller;


class NotifyController extends  BaseController{
    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 产品列表
     */
    public function index($ajax=0){
        $map=$this->_search();
        //排序
        $ordermap = 'id desc';

        if($ajax){
            $this->ajaxReturn($this->get_ajax_list(M('article'), $map, $ordermap,'','id,title,content'));
        }else{
            $this->list=$list=$this->getlist(M('article'),$map,$ordermap);
            $this->col=$col=M('column')->where('fid=3')->select();
            $this->display();
        }

    }

    public function add(){
        $this->col=$col=M('column')->where('fid=3')->select();
       $this->display();
    }
    public function addhd(){
        if(IS_POST){
            $data = $this->_make_attr($_POST['attr']);

            $article = array(
                'title'=>I('post.title'),
                'cid'=>I('post.cid'),
                'content'=>I('post.content'),
                'sort'=>I('post.sort'),
                'description'=>I('post.description'),
                'status'=>$_POST['status']?I('post.status'):0,
                'create_time'=>time()
            );
            $article = array_merge($article,$data);

            if(!D('article')->add($article)){
                $this->ajaxReturn(array('status'=>0,'msg'=>'添加失败请重试'));
            }
            $this->ajaxReturn(array('status'=>1,'msg'=>'添加成功'));
        }
    }
    public function edit(){
        $id=I('get.id',intval);
        $pro = M('article')->find($id);
        $this-> arc =$pro;
        $this->col=$col=M('column')->field('id,title')->where('fid=3')->select();
        $this->display();
    }

    public function edithd(){
        if(IS_POST){
            $data = $this->_make_attr($_POST['attr']);
            $article = array(
                'id'=>I('post.id'),
                'title'=>I('post.title'),
                'cid'=>I('post.cid'),
                'content'=>I('post.content'),
                'description'=>I('post.description'),
                'sort'=>I('post.sort'),
                'status'=>$_POST['status']?I('post.status'):0,
                'time'=>time()
            );
            $article = array_merge($article,$data);

            if(!D('article')->save($article)){
                $this->ajaxReturn(array('status'=>0,'msg'=>'修改失败'));
            }
            $this->ajaxReturn(array('status'=>1,'msg'=>'修改成功'));
        }
    }

    /**
     * 删除
     */
    public function del(){
        $id = I('get.id',intval);
        if(!M('article')->delete($id)){
            $this->ajaxReturn(array('status'=>0,'msg'=>'删除失败，请重试'));
        }
        $this->ajaxReturn(array('status'=>1,'msg'=>'删除成功'));
    }
    /**
     * @return array
     */
    protected function _search() {
        $map = array();
        $title = I('get.title','', 'trim');

        if($title){
            $map['title'] = array('like',array('%'.$title.'%'));
        }

        //状态（正常，禁用）
        if ($_GET['cid'] == -1 || $_GET['cid'] == null) {
            $status = '';
        } else {
            $status = intval($_GET['cid']);
            $map['cid'] = array('eq', $status);
        }

        //输出
        $this->assign('search', array(
            'name' => $title,
            'status' => $status,
        ));

        return $map;
    }

    protected function _make_attr($attr){
        $_temp=array('com','hot','new','head','top');
        foreach ($_temp as $v){
            if($attr[$v]==1){
                $_result[$v]=1;
            }else{
                $_result[$v]=0;
            }
        }
        return $_result;
    }
}