<?php
//000000000060a:12:{i:0;a:12:{s:2:"id";s:2:"11";s:5:"title";s:12:"股票灯塔";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160530/20160530123627_79265.png";s:7:"content";s:5653:"&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt; 
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;一&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;句话介绍：&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;您的智能选股专家&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&amp;nbsp;&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;应用介绍：&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;＊＊＊&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;灯塔财经，您的智能选股专家！&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;＊＊＊&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;「新股民，不迷茫」&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;智能选股，灯塔财经专为新股民每天推荐优绩股，策略说明清晰明了，评测图表直击痛点，让股市从未如此清晰！&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;「老股民，效率高」&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;态度新闻，灯塔财经专为老股民打造了有态度的股市新闻，每篇财经新闻提炼摘要，标记金融态度，利好利空一眼便知，让炒股从未如此轻松！&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&amp;nbsp;&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;————牛市会涨不重要，如何选股才重要！&amp;nbsp;————&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;灯塔，一款全新视角的智能炒股，证券，投资软件。告别老式的专家分析，告别复杂的&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;K&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;线图，为您独家打造可视化数据解读，我们希望给您带来一款有洞见、有品质、有温度的炒股神器。&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;［爱上灯塔］&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;1.&amp;nbsp;态度分析：影响交易的资讯摘要提炼，独家解读，利好利空一目了然；&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;2.&amp;nbsp;智能选股：消息面、基本面、技术面，总有一个策略适合你；&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;3.&amp;nbsp;热点主题：全网扫描，概念、题材，市场热点轻松捕捉；&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;4.&amp;nbsp;个股画像：多维分析个股行情、业绩、估值、评级，挑出牛股你也可以；&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;5.&amp;nbsp;全球行情：&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;A&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;股、港股、美股、全球免费实时行情，一站式供你享用；&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;［联系我们］&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;用户&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;QQ&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;群&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;:470582779&lt;/span&gt; 
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;微信公众号：股票灯塔（微信&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;ID&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;：&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;gupiaodt&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;）&lt;/span&gt; 
&lt;/p&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt; 
&lt;div style=&quot;text-align:center;&quot;&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530123905_91675.png&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530123905_58414.png&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530123905_78267.png&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530123906_31435.png&quot; alt=&quot;&quot; /&gt; 
&lt;/div&gt;
&lt;/span&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.5";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464583185";}i:1;a:12:{s:2:"id";s:2:"17";s:5:"title";s:9:"360卫士";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622154033_32417.jpg";s:7:"content";s:3123:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;结算：真实量，不作弊 按安装结算&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/2824741.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;360手机卫士&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;是一款免费的&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/6950372.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;手机安全软件&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;，集防垃圾短信，防骚扰电话，防隐私泄漏，对手机进行安全&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/252989.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;扫描&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;，联网云查杀恶意&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/subview/37/6030295.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;软件&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;，软件安装实时检测，&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/subview/66422/13091236.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;流量&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;使用全掌握，&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/25302.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;系统&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;清理手机加速，归属地显示及查询等功能于一身，是一款功能全面的智能手机安全软件。&lt;/span&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622153205_83330.png&quot; alt=&quot;&quot; /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.5";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1466580732";}i:2;a:12:{s:2:"id";s:2:"12";s:5:"title";s:6:"大卡";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160530/20160530124235_97158.png";s:7:"content";s:2584:"&lt;span style=&quot;font-size:14px;&quot;&gt;找货、加油，卡车车机定位用车旺大卡，找车找货利器，货主发货助手。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;车旺大卡除了整合货运信息网的信息外，还有百万卡友实时发布的海量卡车货运信息，真实可靠。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;如果你有找货需求，车旺大卡可以让你一分钟找到真实可靠的货源信息，快速省钱，让找货不再困难；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;如果你有找车配货运输需求，车旺大卡上数万计的车主、车队、物流企业等着你，运费更低，通过实名认证和车主认证判断承运人的身份，让货物运送无忧；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;如果你有二手卡车买卖的交易需求，车旺大卡值得拥有，车旺大卡会让你在短时间内挑选到或卖出车辆，信息有保障；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;如果你还在为油价上涨而担心加油成本，车旺大卡更是加油省钱的利器，车旺大卡整合了原车旺加油卡功能，不间断的线上活动让你加油券拿到手软，在加油上享受到更大的优惠，加油省钱就用车旺大卡。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;让找车配货变得简单、让加油优惠成为常态、让管车定位、路况分析随时随地查看，跟同行交流心得，卡车货运行业新闻资讯一手掌握，为车主、货主、第三方物流、物流企业等提供聊天沟通社交功能，让您感受专属货运人的“互联网+”的智能车联网大数据生活，车旺大卡将带给您更加丰富的服务!&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;相关软件：车旺、卡车之家、汽车之家、货车帮、卡团、路歌、运满满、罗计等。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;车旺大卡官方客服电话：400-815-5656&lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;车旺大卡官方客服邮箱：daka@sinoiov.com&lt;/span&gt;
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530124413_49570.png&quot; alt=&quot;&quot; /&gt;&lt;br /&gt;
&lt;/span&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.3";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464583499";}i:3;a:12:{s:2:"id";s:2:"20";s:5:"title";s:12:"平安好房";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622163121_94983.jpg";s:7:"content";s:3223:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;注释：次留30% 周留10% 激活到注册30% &amp;nbsp; 回访80%。目前定向北京上海。&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;&lt;br /&gt;
&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;平安好房是平安集团旗下专业的房产金融界利器。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;优质楼盘独家特惠，金融产品，再得收益！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;【平安好房特色】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;1、好房宝：集互联网、金融、房地产于一身的跨界产品；综合收益率高达4%；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;2、 按揭贷：利率低，放款快，多家银行合作，总有一款适合你！；&lt;/span&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;3、 房贷计算器：最新的计算利率，让您的房贷计算更加精准；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;4、新房楼盘：量大价低，独家特惠，超强购房补贴；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;5、二手房：提供专属您的经纪人，为您提供一对一看房服务。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;6、租房：线上交易，海量真实房源等你选。&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span&gt;&lt;span style=&quot;font-size:14px;line-height:21px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span&gt;&lt;span style=&quot;font-size:14px;line-height:21px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span&gt;&lt;span style=&quot;font-size:14px;line-height:21px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p style=&quot;color:#E53333;font-size:16px;text-align:center;&quot;&gt;
	&lt;span style=&quot;color:#333333;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160622/20160622163558_53520.png&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160622/20160622163559_64902.png&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160622/20160622163559_64281.png&quot; alt=&quot;&quot; /&gt;&amp;nbsp; &amp;nbsp;&amp;nbsp;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160622/20160622163559_57056.png&quot; alt=&quot;&quot; /&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p style=&quot;color:#E53333;font-size:16px;text-align:center;&quot;&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p style=&quot;color:#E53333;font-size:16px;text-align:center;&quot;&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.5";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1466584740";}i:4;a:12:{s:2:"id";s:2:"13";s:5:"title";s:5:"17173";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160530/20160530130557_14228.png";s:7:"content";s:3832:"&lt;span style=&quot;font-size:14px;&quot;&gt;游戏门户17173官方APP，超好玩的手游综合娱乐社区，专注于为玩家提供更优质的手游服务，内容涵盖资讯、视频、攻略、囧图、美女视频直播、游戏直播&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;良心，只推荐真正好玩的手机游戏！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;原创，专业编辑团队呕血打造！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;专业，中国强影响力的游戏媒体！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;娱乐，恶搞囧图奇葩大咖爆笑来袭！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;独门绝技：&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;&amp;nbsp;【游戏资讯】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;游戏圈动态权威发布，实时掌握新鲜的游戏资讯，从游戏八卦到行业信息，麻辣酸甜，您关注神马就有神马！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;.【游戏攻略】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;原创手游攻略：部落冲突、海岛奇兵、英雄联盟（lol)、穿越火线、天天酷跑、梦幻西游、炉石传说、刀塔传奇、自由之战、我叫MT2、天龙八部3D等热门攻略应有尽有。从新手入门到大神教学,从主流打法到独门秘籍，助你成功走上游戏大神之路；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;.【游戏视频】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;.专属于你的游戏视频库，新游预告，名嘴解说，通关攻略，热门比赛，娱乐搞笑应有尽有，高清离线播不错过一丝精彩；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;.【游戏直播】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;口袋里的游戏赛事直播中心，热门赛事实时直播，水友对战天天都有，人气大神亲临现场，为你实时呈现精彩赛事；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;.【视频直播】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;玩家更爱的真人美女视频直播社区，这里是能歌、能侃、能喊、能舞，各路帅哥妹子集中营。快来下载17173游戏，让您不再成为寂寞的围观者。&amp;nbsp;&lt;/span&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;【基本信息】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;作者：北京冠游时空数码技术有限公司 更新时间：2016-04-20&amp;nbsp;&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;版本：3.4.0100 系统：Android 2.2.x以上&amp;nbsp;&lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;语言：中文&amp;nbsp;&lt;/span&gt; 
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530130712_74035.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530130712_61872.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530130712_22297.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530130713_73733.jpg&quot; alt=&quot;&quot; /&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;div&gt;
	&lt;br /&gt;
&lt;/div&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.4";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1464584871";}i:5;a:12:{s:2:"id";s:2:"18";s:5:"title";s:14:"51苹果助手";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622155700_95913.jpg";s:7:"content";s:3863:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;注释：ios产品 &amp;nbsp;只要safari的量&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;background-color:#FFFFFF;&quot;&gt;i苹果助手 是一款为&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/subview/158983/10978793.htm&quot;&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;ios&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;background-color:#FFFFFF;&quot;&gt;设备提供资源的平台，为用户提供海量的游戏、软件、电子书，通过这款软件可快速下载、安装、管理手机资源。手机在无需越狱的情况下就可以免费安装正版应用。&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;font-family:'Microsoft YaHei', SimHei, Verdana;line-height:1.5;background-color:#FFFFFF;&quot;&gt;&lt;strong&gt;使用帮助&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;
	&lt;ol class=&quot;para-list list-paddingleft-2&quot; style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
		&lt;li&gt;
			&lt;div class=&quot;para&quot; style=&quot;font-size:14px;margin-left:25px;&quot;&gt;
				&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;安装[1]&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;&amp;nbsp; ：首次安装i苹果电脑版，程序会自动检测电脑里是否已经安装了苹果驱动。如果没有安装，i苹果会自动帮您下载和安装。如果提示苹果&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/subview/43111/5071586.htm&quot;&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;驱动&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;安装失败，需要到苹果官网手动下载并安装&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/365842.htm&quot;&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;iTunes&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;软件，如果手动安装iTunes仍然失败，建议重启电脑&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;。&lt;/span&gt;
			&lt;/div&gt;
		&lt;/li&gt;
		&lt;li&gt;
			&lt;div class=&quot;para&quot; style=&quot;font-size:14px;margin-left:25px;&quot;&gt;
				&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;闪退修复[2&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;：将手机与电脑连接，打开i苹果电脑版中“我的手机”页面，选择左侧目录中的“&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/8908494.htm&quot;&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;闪退&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;修复”选项，即可进行闪退修复&lt;/span&gt;
			&lt;/div&gt;
		&lt;/li&gt;
	&lt;/ol&gt;
	&lt;div style=&quot;text-align:center;&quot;&gt;
		&lt;span style=&quot;line-height:1.5;&quot;&gt;&lt;/span&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622160418_54906.png&quot; alt=&quot;&quot; /&gt;
	&lt;/div&gt;
&lt;/span&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.8";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1466582678";}i:6;a:12:{s:2:"id";s:2:"14";s:5:"title";s:6:"神交";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160530/20160530133741_92032.png";s:7:"content";s:3084:"&lt;span style=&quot;font-size:14px;&quot;&gt;【简介】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;神交是款用表情约玩的APP，专注于熟人吃喝玩乐，能马上发现朋友的玩乐状态，还能约到朋友的朋友，比逐个约朋友快100倍!&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;【功能】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;表情约玩：6个表情发现玩乐朋友,&amp;nbsp;直接一键邀约，简单快速&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;约朋友玩：只有朋友才能约，防止骚扰&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;朋友的朋友：系统自动推荐可能认识的人，和朋友的朋友建立关系&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;快速约起：勾勾手指马上约起，约朋友玩只需2步&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;【特点】&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;表情约玩&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;6个表情马上发现玩乐朋友，还能智能匹配时间距离，直接一键邀约，简单快速&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;约朋友玩&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;熟人圈子新玩法，好友才能约，迅速建立熟人圈子关系&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;朋友的朋友&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;上传通讯录后系统自动推荐可能认识的人，和朋友的朋友建立关系，拓展社交圈&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;快速约起&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;打一句“有空吃饭吗？”需要敲17次键盘，在这里只需勾勾手指，约人两步走&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;官方网站：http://mindate.cn/&lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;微信公众号：神交Mindate&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530135312_80486.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530135312_53619.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530135312_41856.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530135312_26345.jpg&quot; alt=&quot;&quot; /&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.7";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1464586912";}i:7;a:12:{s:2:"id";s:2:"15";s:5:"title";s:12:"魔秀桌面";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160530/20160530142502_93069.png";s:7:"content";s:3390:"&lt;span style=&quot;font-size:14px;&quot;&gt;魔秀桌面介绍：&lt;/span&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;魔秀主题桌面--亿万用户都在用的主题桌面，让手机更快、更美、更懂你！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;★魔秀桌面，为美而生，千万款精美主题免费下载，可在线制作专属主题★&amp;nbsp;&lt;/span&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;=====【产品亮点】=====&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;▲精美主题—安卓个性主题壁纸免费下载，小鲜肉、女神、喵星人、火影忍者、航海王、angelababy、吴磊、鹿晗、李易峰、吴亦凡、tfboys主题桌面风格多样！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;▲超小内存—比同类小300%，不占空间，不耗电，省流量，无卡顿!&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;▲畅快体验—系统运行流畅，桌面响应迅速，快速打开APP！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;▲智能分类—应用分类智能整理，人性化操作体验，简约更时尚！&lt;/span&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;=====【特色功能】=====&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;【制作主题】支持在线制作主题，无需ps，定制个性美美哒主题桌面；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;【极速搜索】万能搜索框，找应用搜热点，一触即达；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;【隐藏应用】不想见的运动减肥铃声字体照片应用，统统不见。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;【生活小部件】一键清理、一键换壁纸，天气预报等多种小部件，生活简单不简约。&lt;/span&gt;&lt;br /&gt;
&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;★关于我们★&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;魔秀团队，狂热于一件事：将您和您需要的服务，高效、便捷又舒适的连接起来！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;魔秀桌面反馈群：73687811&lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;微信公众号：moxiu520&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530142746_50633.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530142747_17900.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530142747_21765.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530142747_65253.jpg&quot; alt=&quot;&quot; /&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.0";s:3:"com";s:5:"CPA_0";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1464589708";}i:8;a:12:{s:2:"id";s:1:"2";s:5:"title";s:18:"海马手机助手";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613142859_78506.png";s:7:"content";s:2564:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt; &lt;/span&gt;
&lt;/p&gt;
&lt;p style=&quot;text-align:left;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;推广要求：&lt;/span&gt;&lt;span style=&quot;line-height:1.5;color:#E53333;font-size:18px;&quot;&gt;&lt;strong&gt;次留25% &amp;nbsp; 周留15% &amp;nbsp; 真实量 &amp;nbsp;有用户行为！！&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;line-height:1.5;font-size:14px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;line-height:1.5;font-size:14px;&quot;&gt;行云流水般的用户体验&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;海马助手是一款无需越狱，无需Apple ID，免费下载安装海量正版资源应用。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;海马助手有着非常优秀的界面体验设计，利用手势操作，栏目布局一目了然。照顾国内用户对资源查找下载安装等习惯，给人不杂不乱的感觉！加之优秀的UI设计，让您体验行云流水般地操作。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;海量资源轻松下载&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;海马助手囊括30万数量的软件、游戏等资源，分门别类、更新迅速，让您随时随地High起来！丰富的软件游戏，铃声，壁纸资源，一键安装，无需多余操作，飞速下载，自动安装，且支持苹果下载过程中不待机掉线，支持后台下载。在你点击需要安装的软件之后，可安home键，做其他的事，海马助手自动帮你下载，待下载完后会提示是否安装。同时像铃声壁纸轻松设置，解决用户设置铃声的不便！&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;飞速下载 风驰电掣&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;海马助手具有覆盖电信、联通、移动三大互联网商的高速网络，让您的下载如风驰电掣！&lt;/span&gt;&lt;br /&gt;
	&lt;div style=&quot;text-align:center;&quot;&gt;
		&lt;span style=&quot;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613143526_61027.jpg&quot; alt=&quot;&quot; /&gt;
	&lt;/div&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_3.8";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345525";}i:9;a:12:{s:2:"id";s:1:"1";s:5:"title";s:12:"暴风影音";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527123554_86434.png";s:7:"content";s:2453:"&lt;p&gt;
	&lt;span style=&quot;color:#E53333;font-size:16px;line-height:1.5;&quot;&gt;&lt;strong&gt;质量要求：真实量，不刷量，不作弊&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124427_91930.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt; &lt;/span&gt; 
&lt;/p&gt;
&lt;div&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;暴风影音软件是由北京暴风网际科技有限公司出品，从2003年开始，暴风就致力于&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;新版暴风影音为互联网用户提供最简单、便捷的互联网音视频播放解决方案。截止2012年末，暴风的工程师分析数以十万计的视频文件，掌握了超过500种视频格式的支持方案。&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;2010年1月12日暴风影音在京推出暴风影音2012版，以传统影音播放为主的暴风影音，独创&quot;SHD&quot;高清专利技术，实现了1M带宽流畅观看720P高清在线视频的先例。在随后的时间内，暴风又以1080P的更高播放画质赢得了众多用户的青睐。业内人士指出，暴风720P高清业务已在业内遥遥领先，推出1080P更是令其他同行无法企及。相对于主流的720P在线高清，暴风影音的1080P在线高清业务是专为宽带环境较好、对画质要求更为极致的用户所打造。经技术人员检测，因为1080P的高质量规格，用户需要在1.5M带宽下才可以流畅播放，但即便如此，相比承诺更高带宽可流畅播放的服务平台，暴风的技术、用户成本优势突出。&lt;br /&gt;
&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.2";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345445";}i:10;a:12:{s:2:"id";s:1:"5";s:5:"title";s:12:"酷我音乐";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613144852_32869.jpg";s:7:"content";s:3218:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;推广要求：&lt;strong&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt;真实量 &amp;nbsp;不刷量 捆绑量等都可以！评分考核.&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt; &lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;酷我音乐是中国数字音乐的交互服务品牌，是互联网领域的数字音乐服务平台，同时也是一款内容全、聆听快和界面炫的音乐聚合播放器，是国内的多种音乐资源聚合的播放软件。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;自平台成立以来，酷我音乐作为前端潮流音乐的重要推手，率先与唱片公司、版权管理机构合作探索发展，免费向广大用户提供方便流畅的在线音乐，还有免费无损音乐方便用户的试听和下载，生成了丰富的音乐流媒体生态系统。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;酷我是由前百度首席架构师雷鸣先生在2005年8月创立的。雷鸣是百度创始七剑客之一，首席架构师。他是百度搜索引擎的早期设计者和技术负责人之一。雷鸣现任酷我音乐董事长和CEO。他获得北京大学计算机科学硕士学位&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;和斯坦福大学商学院MBA学位，曾任北京大学计算机系学生会主席和斯坦福大学中国学生学者联合会副主席。雷鸣是国家千人计划特聘专家，北京市海聚工程特聘专家&lt;/span&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;font-size:16px;&quot;&gt; 
&lt;div style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;line-height:1.5;&quot;&gt;&lt;/span&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613145012_77346.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/div&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.3";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464346358";}i:11;a:12:{s:2:"id";s:2:"19";s:5:"title";s:12:"酷我音乐";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622161333_46680.jpg";s:7:"content";s:2547:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;注释：真实渠道，报备推广地址，评分考核质量&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;
	&lt;div class=&quot;para&quot; style=&quot;margin:0px;padding:0px;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
		&lt;span style=&quot;line-height:2;&quot;&gt;酷我音乐是中国数字音乐的交互服务品牌，是互联网领域的数字音乐服务平台，同时也是一款内容全、聆听快和界面炫的音乐聚合播放器，是国内的多种音乐资源聚合的播放软件。&lt;/span&gt;
	&lt;/div&gt;
	&lt;div class=&quot;para&quot; style=&quot;margin:0px;padding:0px;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
		&lt;span style=&quot;line-height:2;&quot;&gt;自平台成立以来，酷我音乐作为前端潮流音乐的重要推手，率先与唱片公司、版权管理机构合作探索发展，免费向广大用户提供方便流畅的在线音乐，还有免费无损音乐方便用户的试听和下载，生成了丰富的音乐流媒体生态系统。&lt;/span&gt;
	&lt;/div&gt;
	&lt;div class=&quot;para&quot; style=&quot;margin:0px;padding:0px;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
		&lt;p&gt;
			&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;&quot;&gt;酷我是由前百度首席架构师雷鸣先生在2005年8月创立的。雷鸣是百度创始七剑客之一，首席架构师。他是百度搜索引擎的早期设计者和技术负责人之一。雷鸣现任酷我音乐董事长和CEO。他获得北京大学计算机科学硕士学位&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;span style=&quot;font-size:14px;line-height:2;&quot;&gt;和斯坦福大学商学院MBA学位，曾任北京大学计算机系学生会主席和斯坦福大学中国学生学者联合会副主席。雷鸣是国家千人计划特聘专家，北京市海聚工程特聘专家&lt;/span&gt;&lt;/span&gt;
		&lt;/p&gt;
	&lt;/div&gt;
	&lt;div style=&quot;text-align:center;&quot;&gt;
		&lt;strong&gt;&lt;img src=&quot;http://cpa88.com/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613145012_77346.jpg&quot; /&gt;&lt;/strong&gt;
	&lt;/div&gt;
&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.3";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1466583628";}}
?>