<?php
//000000000060a:3:{i:0;a:12:{s:2:"id";s:1:"5";s:5:"title";s:12:"酷我音乐";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613144852_32869.jpg";s:7:"content";s:3181:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;推广要求：&lt;strong&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt;真实量 &amp;nbsp;不刷量&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt; &lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;酷我音乐是中国数字音乐的交互服务品牌，是互联网领域的数字音乐服务平台，同时也是一款内容全、聆听快和界面炫的音乐聚合播放器，是国内的多种音乐资源聚合的播放软件。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;自平台成立以来，酷我音乐作为前端潮流音乐的重要推手，率先与唱片公司、版权管理机构合作探索发展，免费向广大用户提供方便流畅的在线音乐，还有免费无损音乐方便用户的试听和下载，生成了丰富的音乐流媒体生态系统。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;酷我是由前百度首席架构师雷鸣先生在2005年8月创立的。雷鸣是百度创始七剑客之一，首席架构师。他是百度搜索引擎的早期设计者和技术负责人之一。雷鸣现任酷我音乐董事长和CEO。他获得北京大学计算机科学硕士学位&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;和斯坦福大学商学院MBA学位，曾任北京大学计算机系学生会主席和斯坦福大学中国学生学者联合会副主席。雷鸣是国家千人计划特聘专家，北京市海聚工程特聘专家&lt;/span&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;font-size:16px;&quot;&gt; 
&lt;div style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;line-height:1.5;&quot;&gt;&lt;/span&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613145012_77346.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/div&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.3";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464346358";}i:1;a:12:{s:2:"id";s:1:"1";s:5:"title";s:12:"暴风影音";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527123554_86434.png";s:7:"content";s:4104:"&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;table style=&quot;width:403px;&quot; align=&quot;center&quot; border=&quot;1&quot; bordercolor=&quot;#CCC&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; height=&quot;135&quot;&gt;
		&lt;tbody&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;推广方式&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;价格&lt;/strong&gt;&lt;strong&gt;&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;结算周期&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPA&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					1.5&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					月结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPS&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					0.5&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					周结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPC&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					0.6&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					日结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
		&lt;/tbody&gt;
	&lt;/table&gt;
&lt;br /&gt;
&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;真实量，不刷量，不作弊&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124427_91930.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt; &lt;/span&gt; 
&lt;/p&gt;
&lt;div&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;暴风影音软件是由北京暴风网际科技有限公司出品，从2003年开始，暴风就致力于&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;新版暴风影音为互联网用户提供最简单、便捷的互联网音视频播放解决方案。截止2012年末，暴风的工程师分析数以十万计的视频文件，掌握了超过500种视频格式的支持方案。&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;2010年1月12日暴风影音在京推出暴风影音2012版，以传统影音播放为主的暴风影音，独创&quot;SHD&quot;高清专利技术，实现了1M带宽流畅观看720P高清在线视频的先例。在随后的时间内，暴风又以1080P的更高播放画质赢得了众多用户的青睐。业内人士指出，暴风720P高清业务已在业内遥遥领先，推出1080P更是令其他同行无法企及。相对于主流的720P在线高清，暴风影音的1080P在线高清业务是专为宽带环境较好、对画质要求更为极致的用户所打造。经技术人员检测，因为1080P的高质量规格，用户需要在1.5M带宽下才可以流畅播放，但即便如此，相比承诺更高带宽可流畅播放的服务平台，暴风的技术、用户成本优势突出。&lt;br /&gt;
&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:11:"CPA,CPS,CPC";s:5:"price";s:23:"CPA_1.5,CPS_0.5,CPC_0.6";s:3:"com";s:17:"CPA_1,CPS_0,CPC_0";s:12:"balance_time";s:17:"CPA_3,CPS_2,CPC_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345445";}i:2;a:12:{s:2:"id";s:1:"8";s:5:"title";s:12:"腾讯视频";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527130627_19374.jpg";s:7:"content";s:1461:"&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;腾讯视频，是定位于中国最大在线视频媒体平台，同时也是一款视频播放器。其以丰富的内容、极致的观看体验、便捷的登录方式、24小时多平台无缝应用体验以及快捷分享的产品特性，满足用户在线观看视频的需求。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;2011年4月，腾讯视频上线测试，使用域名为原腾讯播客域名，腾讯QQLive网站已被纳入到腾讯视频中同步运作。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;2015年2月12日，2015年央视春晚落户腾讯视频。[1] &lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;2016年3月24日，全网独播马克、张馨予领衔主演的《重生之名流巨星》，直接从当贝市场下载腾讯视频TV版即可观看。[2-4]&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;div align=&quot;center&quot;&gt;
	&lt;p&gt;
		&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527130740_57400.png&quot; alt=&quot;&quot; /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
&lt;/div&gt;";s:4:"type";s:1:"1";s:4:"attr";s:7:"CPA,CPS";s:5:"price";s:15:"CPA_1.2,CPS_0.6";s:3:"com";s:11:"CPA_0,CPS_1";s:12:"balance_time";s:11:"CPA_3,CPS_3";s:7:"service";s:1:"2";s:11:"create_time";s:10:"1464347266";}}
?>