<?php
//000000000060a:5:{i:0;a:12:{s:2:"id";s:1:"5";s:5:"title";s:12:"酷我音乐";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613144852_32869.jpg";s:7:"content";s:3218:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;推广要求：&lt;strong&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt;真实量 &amp;nbsp;不刷量 捆绑量等都可以！评分考核.&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt; &lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;酷我音乐是中国数字音乐的交互服务品牌，是互联网领域的数字音乐服务平台，同时也是一款内容全、聆听快和界面炫的音乐聚合播放器，是国内的多种音乐资源聚合的播放软件。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;自平台成立以来，酷我音乐作为前端潮流音乐的重要推手，率先与唱片公司、版权管理机构合作探索发展，免费向广大用户提供方便流畅的在线音乐，还有免费无损音乐方便用户的试听和下载，生成了丰富的音乐流媒体生态系统。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;酷我是由前百度首席架构师雷鸣先生在2005年8月创立的。雷鸣是百度创始七剑客之一，首席架构师。他是百度搜索引擎的早期设计者和技术负责人之一。雷鸣现任酷我音乐董事长和CEO。他获得北京大学计算机科学硕士学位&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;和斯坦福大学商学院MBA学位，曾任北京大学计算机系学生会主席和斯坦福大学中国学生学者联合会副主席。雷鸣是国家千人计划特聘专家，北京市海聚工程特聘专家&lt;/span&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;font-size:16px;&quot;&gt; 
&lt;div style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;line-height:1.5;&quot;&gt;&lt;/span&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613145012_77346.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/div&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.3";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464346358";}i:1;a:12:{s:2:"id";s:2:"19";s:5:"title";s:12:"酷我音乐";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622161333_46680.jpg";s:7:"content";s:2547:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;注释：真实渠道，报备推广地址，评分考核质量&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;
	&lt;div class=&quot;para&quot; style=&quot;margin:0px;padding:0px;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
		&lt;span style=&quot;line-height:2;&quot;&gt;酷我音乐是中国数字音乐的交互服务品牌，是互联网领域的数字音乐服务平台，同时也是一款内容全、聆听快和界面炫的音乐聚合播放器，是国内的多种音乐资源聚合的播放软件。&lt;/span&gt;
	&lt;/div&gt;
	&lt;div class=&quot;para&quot; style=&quot;margin:0px;padding:0px;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
		&lt;span style=&quot;line-height:2;&quot;&gt;自平台成立以来，酷我音乐作为前端潮流音乐的重要推手，率先与唱片公司、版权管理机构合作探索发展，免费向广大用户提供方便流畅的在线音乐，还有免费无损音乐方便用户的试听和下载，生成了丰富的音乐流媒体生态系统。&lt;/span&gt;
	&lt;/div&gt;
	&lt;div class=&quot;para&quot; style=&quot;margin:0px;padding:0px;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
		&lt;p&gt;
			&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;&quot;&gt;酷我是由前百度首席架构师雷鸣先生在2005年8月创立的。雷鸣是百度创始七剑客之一，首席架构师。他是百度搜索引擎的早期设计者和技术负责人之一。雷鸣现任酷我音乐董事长和CEO。他获得北京大学计算机科学硕士学位&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;span style=&quot;font-size:14px;line-height:2;&quot;&gt;和斯坦福大学商学院MBA学位，曾任北京大学计算机系学生会主席和斯坦福大学中国学生学者联合会副主席。雷鸣是国家千人计划特聘专家，北京市海聚工程特聘专家&lt;/span&gt;&lt;/span&gt;
		&lt;/p&gt;
	&lt;/div&gt;
	&lt;div style=&quot;text-align:center;&quot;&gt;
		&lt;strong&gt;&lt;img src=&quot;http://cpa88.com/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613145012_77346.jpg&quot; /&gt;&lt;/strong&gt;
	&lt;/div&gt;
&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.3";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1466583628";}i:2;a:12:{s:2:"id";s:2:"21";s:5:"title";s:9:"财金圈";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160623/20160623144658_80998.jpg";s:7:"content";s:5743:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;注释：不刷量、不作弊，真实量。&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:#333333;&quot;&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;大转盘抽奖“赚”不停！魔兽电影票、财金圈定制&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;U&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;盘免费送！万元体验金、海量现金红包等你来拿！&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;【新人专享福利多】&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;新人见面，好礼相送：新人专享&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;18888&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;元体验金，&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;7%&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;年化收益，&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;1&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;天后体验金投资收益归个人所有。&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;【感恩回馈有惊喜】&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;定期感恩回馈活动，现金红包、实物好礼送不停！让您回报多多惊喜连连！&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;【产品丰富收益高】&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;活期宝最高年化收益8%，3-24月定期标，定期收益最高13%，满足多样化投资需求，带您进入安全便捷理财时代，更高收益看得见！&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;【安全投资有保障】&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;资金安全：第三方国家级支付公司资金托管。&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;账户安全：账户网络安全由太平洋财产保险承保。&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;风控安全：31道严格审核＋中央财经大学教授团队研发的“云鼎”大数据风控系统。&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;交易安全：注册用户双认证，资金同卡进出零风险。&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;数据安全：携手阿里云、沃通，采用国际领先的系统加密及保护技术，确保用户信息安全。&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;【贵宾服务更贴心】&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;客服热钱：400-681-3066（周一至周五：9:00-19:00）&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;官方微信：财金圈订阅（caijinquandy）&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;官方微博：财金圈官微&lt;/span&gt;
	&lt;/p&gt;
	&lt;p class=&quot;MsoNormal&quot;&gt;
		&lt;span style=&quot;font-size:14px;&quot;&gt;理财首选财金圈，掌上理财，点时成金！财金圈是由中央财经大学科技园重点孵化的一款高收益安全优质理财&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;APP&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;，&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;100&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;元起投，收益最高&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;13%&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;，迄今为止&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;100%&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;还本付息&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;0&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;逾期，让每个用心理财的人轻松实现财富增值的梦想！&lt;/span&gt;
	&lt;/p&gt;
&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:#333333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:#333333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;&lt;span style=&quot;color:#333333;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160623/20160623145151_60471.png&quot; alt=&quot;&quot; /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.2";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1466664719";}i:3;a:12:{s:2:"id";s:1:"3";s:5:"title";s:12:"搜狐视频";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613150514_71845.jpg";s:7:"content";s:2280:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;&quot;&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;搜狐视频是知名的网络长视频播放平台，国内第一家提供提供正版、高清、原创视频的门户网站。搜狐视频是'搜狐视频'推出的手机客户端软件，涵盖电影、电视剧、动漫、综艺、纪录片、原创等精彩视频。搜狐视频界面时尚、速度流畅、操作简单，支持高清视频、离线下载，为广大用户提供一站式视频播放解决方案。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;功能&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;1、每日推荐最新电视剧、电影等&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;2、热播排行榜&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;3、详细分类查找功能&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;4、快速搜索、语音搜索&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;5、收藏功能&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;6、评论功能&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;7、视频下载（预加载）功能，支持边加载边看&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;8、播放记录功能&lt;/span&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;&quot;&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160613/20160613151922_41427.jpg&quot; alt=&quot;&quot; /&gt;&amp;nbsp; &amp;nbsp;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160613/20160613151922_31400.jpg&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160613/20160613151923_91759.jpg&quot; alt=&quot;&quot; /&gt;&amp;nbsp; &amp;nbsp;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160613/20160613151923_40615.jpg&quot; alt=&quot;&quot; /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.2";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345629";}i:4;a:12:{s:2:"id";s:1:"9";s:5:"title";s:9:"淘宝网";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527130913_67546.jpg";s:7:"content";s:1838:"&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;淘宝网是亚太地区较大的网络零售、商圈，由阿里巴巴集团在2003年5月创立。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;淘宝网是中国深受欢迎的网购零售平台，拥有近5亿的注册用户数，每天有超过6000万的固定访客，同时每天的在线商品数已经超过了8亿件，平均每分钟售出4.8万件商品。截止2011年年底，淘宝网单日交易额峰值达到43.8亿元，创造270.8万直接 且充分就业机会。随着淘宝网规模的扩大和用户数量的增加，淘宝也从单一的C2C网络集市变成了包括C2C、团购、分销、拍卖等多种电子商务模式在内的综合性零售商圈。目前已经成为世界范围的电子商务交易平台之一。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;2016年3月15日，315晚会曝光，淘宝商家存在刷单等欺骗消费者现象。[1] &lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;2016年3月29日，阿里巴巴集团CEO张勇为淘宝的未来明确了战略：社区化、内容化和本地生活化是三大方向。[2] &lt;br /&gt;
&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527131109_46826.jpg&quot; alt=&quot;&quot; /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;
&lt;/p&gt;
&lt;br /&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.8";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464347474";}}
?>