<?php
//000000000060a:10:{i:0;a:12:{s:2:"id";s:1:"1";s:5:"title";s:12:"暴风影音";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527123554_86434.png";s:7:"content";s:4104:"&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;table style=&quot;width:403px;&quot; align=&quot;center&quot; border=&quot;1&quot; bordercolor=&quot;#CCC&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; height=&quot;135&quot;&gt;
		&lt;tbody&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;推广方式&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;价格&lt;/strong&gt;&lt;strong&gt;&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;结算周期&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPA&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					1.5&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					月结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPS&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					0.5&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					周结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPC&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					0.6&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					日结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
		&lt;/tbody&gt;
	&lt;/table&gt;
&lt;br /&gt;
&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;真实量，不刷量，不作弊&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124427_91930.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt; &lt;/span&gt; 
&lt;/p&gt;
&lt;div&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;暴风影音软件是由北京暴风网际科技有限公司出品，从2003年开始，暴风就致力于&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;新版暴风影音为互联网用户提供最简单、便捷的互联网音视频播放解决方案。截止2012年末，暴风的工程师分析数以十万计的视频文件，掌握了超过500种视频格式的支持方案。&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;2010年1月12日暴风影音在京推出暴风影音2012版，以传统影音播放为主的暴风影音，独创&quot;SHD&quot;高清专利技术，实现了1M带宽流畅观看720P高清在线视频的先例。在随后的时间内，暴风又以1080P的更高播放画质赢得了众多用户的青睐。业内人士指出，暴风720P高清业务已在业内遥遥领先，推出1080P更是令其他同行无法企及。相对于主流的720P在线高清，暴风影音的1080P在线高清业务是专为宽带环境较好、对画质要求更为极致的用户所打造。经技术人员检测，因为1080P的高质量规格，用户需要在1.5M带宽下才可以流畅播放，但即便如此，相比承诺更高带宽可流畅播放的服务平台，暴风的技术、用户成本优势突出。&lt;br /&gt;
&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:11:"CPA,CPS,CPC";s:5:"price";s:23:"CPA_1.5,CPS_0.5,CPC_0.6";s:3:"com";s:17:"CPA_1,CPS_0,CPC_0";s:12:"balance_time";s:17:"CPA_3,CPS_2,CPC_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345445";}i:1;a:12:{s:2:"id";s:1:"2";s:5:"title";s:18:"腾讯电脑管家";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527123802_15754.png";s:7:"content";s:1459:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;真实量，不刷量，不作弊&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124729_71938.jpg&quot; alt=&quot;&quot; /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;腾讯电脑管家（Tencent PC Manager/原名QQ电脑管家）是腾讯公司推出的免费安全软件。拥有云查杀木马，系统加速，漏洞修复，实时防护，网速保护，电脑诊所，健康小助手等功能，首创“管理+杀毒”2合1的开创性功能依托管家云查杀引擎和第二代自研反病毒引擎“鹰眼”，小红伞(antivir) 杀毒引擎和管家系统修复引擎，拥有QQ账号全景防卫系统，针对网络钓鱼欺诈及盗号打击方面，在安全防护及病毒查杀方面的能力已达到国际一流杀软水平。已获得英国西海岸CheckMark认证，VB100认证和AV-C认证，已斩获全球三大权威评测大满贯的成绩[1]&amp;nbsp; 。&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:7:"CPC,CPM";s:5:"price";s:15:"CPC_0.4,CPM_0.3";s:3:"com";s:11:"CPC_1,CPM_0";s:12:"balance_time";s:11:"CPC_3,CPM_2";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345525";}i:2;a:12:{s:2:"id";s:1:"3";s:5:"title";s:12:"搜狐影音";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527123926_98758.png";s:7:"content";s:2460:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;CPM-真实量，不刷量，不作弊&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124217_89021.jpg&quot; alt=&quot;&quot; /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt;&lt;span style=&quot;font-size:14px;color:#333333;line-height:1.5;&quot;&gt; &lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;div&gt;
	&lt;span style=&quot;line-height:2;font-size:14px;&quot;&gt;搜狐影音是搜狐公司出品的，主要功能是为观看sohu视频的用户提供超速加载，最新版本为2013年10月31日发布的“4.2版”。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;line-height:2;font-size:14px;&quot;&gt;该软件采用全新内核并嵌入智能模块，保证了对所有视频的高速加载，并且具有断点续传和记忆下载等功能。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;line-height:2;font-size:14px;&quot;&gt;搜狐影音是搜狐视频强势推出的一款全新体验的播放器。支持主流媒体格式的视频、音频文件，实现本地播放和在线点播。独创2d与3d&amp;nbsp;的easy转换模式，全新的加速模式、结合丰富的在线视频内容、让视频观看更高速、更便捷、更有趣。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;line-height:2;font-size:14px;&quot;&gt;搜狐影音是搜狐视频客户端软件，是一款全新的视频加速播放器，除了可以播放搜狐视频官方网站的影视资源，还可以播放优酷、土豆、腾讯、迅雷等其他视频网站上的资源，也可以播放本地下载的视频文件，并且拥有电视直播功能，可以在线直播数百个高清频道。搜狐影音播放器采用全新下载引擎及预加载功能，让视频点播直播更快速更顺畅更高效。&lt;/span&gt; 
&lt;/div&gt;
&lt;br /&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:11:"CPA,CPS,CPC";s:5:"price";s:23:"CPA_1.5,CPS_0.3,CPC_0.2";s:3:"com";s:17:"CPA_1,CPS_0,CPC_0";s:12:"balance_time";s:17:"CPA_1,CPS_2,CPC_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345629";}i:3;a:12:{s:2:"id";s:1:"4";s:5:"title";s:12:"百度卫士";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124828_46573.png";s:7:"content";s:822:"&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;百度卫士是百度公司出品的简单可信赖的系统工具软件，集电脑加速、系统清理、安全维护三大功能于一身，为用户提供优质的电脑及网络安全服务。此外，百度卫士悬浮窗还可以一键搜索，并智能感知电脑、办公各类问题，提供一键解决方案！百度卫士竭力为用户提供轻巧、快速、智能、纯净的产品体验，同时郑重承诺：永久免费、不骚扰用户、不胁迫用户、不偷窥用户隐私。&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124937_19791.jpg&quot; alt=&quot;&quot; /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:11:"CPA,CPS,CPC";s:5:"price";s:23:"CPA_1.3,CPS_0.6,CPC_0.4";s:3:"com";s:17:"CPA_1,CPS_0,CPC_0";s:12:"balance_time";s:17:"CPA_3,CPS_2,CPC_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464346195";}i:4;a:12:{s:2:"id";s:1:"5";s:5:"title";s:15:"猎豹浏览器";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527125040_57345.png";s:7:"content";s:1735:"&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;猎豹安全浏览器，是由猎豹移动公司（原金山网络）推出的一款浏览器，主打安全与极速特性，采用Trident和WebKit双渲染引擎，并整合金山自家的BIPS进行安全防护。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;猎豹安全浏览器对Chrome的Webkit内核进行了超过100项的技术优化，访问网页速度更快。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;其具有首创的智能切换引擎，动态选择内核匹配不同网页，并且支持HTML5新国际网页标准，极速浏览的同时也保证兼容性。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;2012年12月，猎豹浏览器获得“2012年度最佳创新产品奖”。&lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;2013年6月19日，正式发布猎豹浏览器手机版。&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527125230_21137.jpg&quot; alt=&quot;&quot; /&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:11:"CPA,CPS,CPC";s:5:"price";s:23:"CPA_1.2,CPS_0.4,CPC_0.2";s:3:"com";s:17:"CPA_1,CPS_0,CPC_0";s:12:"balance_time";s:17:"CPA_3,CPS_3,CPC_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464346358";}i:5;a:12:{s:2:"id";s:1:"6";s:5:"title";s:9:"爱奇艺";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527125321_90804.png";s:7:"content";s:1582:"&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;爱奇艺，原名奇艺。2010年4月22日，奇艺正式上线，2011年11月26日，奇艺正式宣布品牌升级，启动“爱奇艺”品牌并推出全新标志。爱奇艺创始人龚宇博士担任CEO。自成立伊始，爱奇艺坚持“悦享品质”的公司理念，以“用户体验”为生命，通过持续不断的技术投入、产品创新，为用户提供清晰、流畅、界面友好的观映体验。2013年5月7日百度收购PPS视频业务，并与爱奇艺进行合并。&lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;2016年2月12日，百度宣布，公司董事会接到公司董事长兼CEO李彦宏和爱奇艺CEO龚宇的初步非约束性收购提议，计划收爱奇艺100%的股份。排除现金及负债交易(cash-free and debt-free，即把现金与负债排除在合约之外)，该交易为爱奇艺估值28亿美元。[1] &lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527130104_14715.jpg&quot; alt=&quot;&quot; /&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:7:"CPA,CPC";s:5:"price";s:15:"CPA_1.8,CPC_0.4";s:3:"com";s:11:"CPA_1,CPC_0";s:12:"balance_time";s:11:"CPA_3,CPC_2";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464346448";}i:6;a:12:{s:2:"id";s:1:"8";s:5:"title";s:12:"腾讯视频";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527130627_19374.jpg";s:7:"content";s:1461:"&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;腾讯视频，是定位于中国最大在线视频媒体平台，同时也是一款视频播放器。其以丰富的内容、极致的观看体验、便捷的登录方式、24小时多平台无缝应用体验以及快捷分享的产品特性，满足用户在线观看视频的需求。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;2011年4月，腾讯视频上线测试，使用域名为原腾讯播客域名，腾讯QQLive网站已被纳入到腾讯视频中同步运作。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;2015年2月12日，2015年央视春晚落户腾讯视频。[1] &lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;2016年3月24日，全网独播马克、张馨予领衔主演的《重生之名流巨星》，直接从当贝市场下载腾讯视频TV版即可观看。[2-4]&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;div align=&quot;center&quot;&gt;
	&lt;p&gt;
		&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527130740_57400.png&quot; alt=&quot;&quot; /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
&lt;/div&gt;";s:4:"type";s:1:"1";s:4:"attr";s:7:"CPA,CPS";s:5:"price";s:15:"CPA_1.2,CPS_0.6";s:3:"com";s:11:"CPA_0,CPS_1";s:12:"balance_time";s:11:"CPA_3,CPS_3";s:7:"service";s:1:"2";s:11:"create_time";s:10:"1464347266";}i:7;a:12:{s:2:"id";s:1:"9";s:5:"title";s:9:"淘宝网";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527130913_67546.jpg";s:7:"content";s:1838:"&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;淘宝网是亚太地区较大的网络零售、商圈，由阿里巴巴集团在2003年5月创立。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;淘宝网是中国深受欢迎的网购零售平台，拥有近5亿的注册用户数，每天有超过6000万的固定访客，同时每天的在线商品数已经超过了8亿件，平均每分钟售出4.8万件商品。截止2011年年底，淘宝网单日交易额峰值达到43.8亿元，创造270.8万直接 且充分就业机会。随着淘宝网规模的扩大和用户数量的增加，淘宝也从单一的C2C网络集市变成了包括C2C、团购、分销、拍卖等多种电子商务模式在内的综合性零售商圈。目前已经成为世界范围的电子商务交易平台之一。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;2016年3月15日，315晚会曝光，淘宝商家存在刷单等欺骗消费者现象。[1] &lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;2016年3月29日，阿里巴巴集团CEO张勇为淘宝的未来明确了战略：社区化、内容化和本地生活化是三大方向。[2] &lt;br /&gt;
&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527131109_46826.jpg&quot; alt=&quot;&quot; /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:2;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;
&lt;/p&gt;
&lt;br /&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.8";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464347474";}i:8;a:12:{s:2:"id";s:2:"12";s:5:"title";s:6:"大卡";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160530/20160530124235_97158.png";s:7:"content";s:2584:"&lt;span style=&quot;font-size:14px;&quot;&gt;找货、加油，卡车车机定位用车旺大卡，找车找货利器，货主发货助手。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;车旺大卡除了整合货运信息网的信息外，还有百万卡友实时发布的海量卡车货运信息，真实可靠。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;如果你有找货需求，车旺大卡可以让你一分钟找到真实可靠的货源信息，快速省钱，让找货不再困难；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;如果你有找车配货运输需求，车旺大卡上数万计的车主、车队、物流企业等着你，运费更低，通过实名认证和车主认证判断承运人的身份，让货物运送无忧；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;如果你有二手卡车买卖的交易需求，车旺大卡值得拥有，车旺大卡会让你在短时间内挑选到或卖出车辆，信息有保障；&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;如果你还在为油价上涨而担心加油成本，车旺大卡更是加油省钱的利器，车旺大卡整合了原车旺加油卡功能，不间断的线上活动让你加油券拿到手软，在加油上享受到更大的优惠，加油省钱就用车旺大卡。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;让找车配货变得简单、让加油优惠成为常态、让管车定位、路况分析随时随地查看，跟同行交流心得，卡车货运行业新闻资讯一手掌握，为车主、货主、第三方物流、物流企业等提供聊天沟通社交功能，让您感受专属货运人的“互联网+”的智能车联网大数据生活，车旺大卡将带给您更加丰富的服务!&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;相关软件：车旺、卡车之家、汽车之家、货车帮、卡团、路歌、运满满、罗计等。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;车旺大卡官方客服电话：400-815-5656&lt;/span&gt;&lt;br /&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;车旺大卡官方客服邮箱：daka@sinoiov.com&lt;/span&gt;
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530124413_49570.png&quot; alt=&quot;&quot; /&gt;&lt;br /&gt;
&lt;/span&gt;
&lt;/p&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.3";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464583499";}i:9;a:12:{s:2:"id";s:2:"11";s:5:"title";s:12:"股票灯塔";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160530/20160530123627_79265.png";s:7:"content";s:5629:"&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;一&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;句话介绍：&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;您的智能选股专家&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&amp;nbsp;&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;应用介绍：&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;＊＊＊&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;灯塔财经，您的智能选股专家！&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;＊＊＊&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;「新股民，不迷茫」&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;智能选股，灯塔财经专为新股民每天推荐优绩股，策略说明清晰明了，评测图表直击痛点，让股市从未如此清晰！&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;「老股民，效率高」&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;态度新闻，灯塔财经专为老股民打造了有态度的股市新闻，每篇财经新闻提炼摘要，标记金融态度，利好利空一眼便知，让炒股从未如此轻松！&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&amp;nbsp;&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;————牛市会涨不重要，如何选股才重要！&amp;nbsp;————&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;灯塔，一款全新视角的智能炒股，证券，投资软件。告别老式的专家分析，告别复杂的&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;K&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;线图，为您独家打造可视化数据解读，我们希望给您带来一款有洞见、有品质、有温度的炒股神器。&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;［爱上灯塔］&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;1.&amp;nbsp;态度分析：影响交易的资讯摘要提炼，独家解读，利好利空一目了然；&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;2.&amp;nbsp;智能选股：消息面、基本面、技术面，总有一个策略适合你；&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;3.&amp;nbsp;热点主题：全网扫描，概念、题材，市场热点轻松捕捉；&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;4.&amp;nbsp;个股画像：多维分析个股行情、业绩、估值、评级，挑出牛股你也可以；&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot; style=&quot;margin-left:4.8000pt;text-indent:-4.8500pt;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;5.&amp;nbsp;全球行情：&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;A&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;股、港股、美股、全球免费实时行情，一站式供你享用；&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;［联系我们］&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;用户&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;QQ&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;群&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;:470582779&lt;/span&gt;
&lt;/p&gt;
&lt;p class=&quot;MsoNormal&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;微信公众号：股票灯塔（微信&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;ID&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;：&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;gupiaodt&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;）&lt;/span&gt;
&lt;/p&gt;
&lt;span style=&quot;font-size:14px;&quot;&gt;
&lt;div style=&quot;text-align:center;&quot;&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530123905_91675.png&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530123905_58414.png&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530123905_78267.png&quot; alt=&quot;&quot; /&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/php/../attached/image/20160530/20160530123906_31435.png&quot; alt=&quot;&quot; /&gt;
&lt;/div&gt;
&lt;/span&gt;";s:4:"type";s:1:"2";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_1.5";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1464583185";}}
?>