<?php
//000000000060a:5:{i:0;a:12:{s:2:"id";s:2:"17";s:5:"title";s:9:"360卫士";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622154033_32417.jpg";s:7:"content";s:3123:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;结算：真实量，不作弊 按安装结算&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/2824741.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;360手机卫士&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;是一款免费的&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/6950372.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;手机安全软件&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;，集防垃圾短信，防骚扰电话，防隐私泄漏，对手机进行安全&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/252989.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;扫描&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;，联网云查杀恶意&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/subview/37/6030295.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;软件&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;，软件安装实时检测，&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/subview/66422/13091236.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;流量&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;使用全掌握，&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/25302.htm&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;系统&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;color:#333333;font-family:arial, 宋体, sans-serif;font-size:14px;line-height:24px;background-color:#FFFFFF;&quot;&gt;清理手机加速，归属地显示及查询等功能于一身，是一款功能全面的智能手机安全软件。&lt;/span&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;span style=&quot;color:#333333;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622153205_83330.png&quot; alt=&quot;&quot; /&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.5";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1466580732";}i:1;a:12:{s:2:"id";s:1:"7";s:5:"title";s:9:"360导航";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160612/20160612133010_81975.png";s:7:"content";s:2646:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;结算：千次IP结算！ &amp;nbsp; &lt;/strong&gt;&lt;/span&gt;&amp;nbsp;&amp;nbsp;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&amp;nbsp;&amp;nbsp;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;360导航是新一代安全上网导航，为用户提供门户、新闻、视频、游戏、小说、彩票等各种分类的优秀内容和网站入口，提供最简单便捷的上网导航服务。安全上网，从360导航开始。[1]&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 360安全网址的宗旨是方便网友们快速找到自已需要的网站，而不用去记太多复杂的网址，我的导航能让网友快速收藏喜爱的网站；同时提供多种搜索引擎入口、实用工具、快速充值、天气预报、团购导航、地方导航等特色服务。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 我们打破了传统网址导航站十几年来一成不变的沉闷局面，首创了“网址+APP聚合”的模式，树立了新一代导航网站的行业标准。我们引领的APP化、个性化、地域化、工具化等特点已经成为业内其他网址站的效仿对象，引领了行业潮流。作为业内最善于创新的网站，360安全网址研发推出了大量新功能。&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160612/20160612130357_92055.jpg&quot; alt=&quot;&quot; /&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;br /&gt;
&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:5:"meiti";s:5:"price";s:8:"meiti_70";s:3:"com";s:7:"meiti_1";s:12:"balance_time";s:7:"meiti_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464347042";}i:2;a:12:{s:2:"id";s:2:"16";s:5:"title";s:6:"好123";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622150940_71588.jpg";s:7:"content";s:3284:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;background-color:#FFFFFF;&quot;&gt;&lt;strong&gt;结算：千次IP结算&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;background-color:#E53333;&quot;&gt;&lt;span style=&quot;background-color:#FFFFFF;&quot;&gt;&lt;/span&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;background-color:#E53333;&quot;&gt; &lt;/span&gt; 
&lt;/p&gt;
&lt;div class=&quot;para&quot; style=&quot;text-align:left;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;hao123是一款快速、功能强大的多窗口&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/8430.htm&quot;&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;上网导航&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;，它是完全免费并没有任何功能限制的上网软件。主要为上网用户提供搜索、热门网站、&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/subview/39315/7029758.htm&quot;&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;天气&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;、股票、彩票、&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/451294.htm&quot;&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;航班&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;、路况、公交等上网常用服务的实用工具，通过hao123上网导航，可以在这里阅读资讯、读小说、看视频、上微博、玩游戏、网上购物、查天气、买彩票，找新闻等，为用户提供便捷的互联网体验。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;text-align:left;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;hao123无线，主要为用户提供搜索、热门网站、天气、股票、彩票、航班、路况、公交、酒店等上网常用服务的实用工具。通过hao123手机上网导航，您可以轻松的阅读最热门的资讯、看更多的免费小说、浏览各种视频、上微博、玩游戏、网上购物、查天气、买彩票等多种服务，为用户提供便捷的移动互联体验！&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;text-align:left;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;hao123始终致力于为用户提供最简单、实用、贴心的上网导航服务。轻松上网，便捷生活，从hao123开始！&lt;/span&gt; 
&lt;/div&gt;
&lt;strong&gt; 
&lt;div style=&quot;text-align:center;&quot;&gt;
	&lt;strong&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;/strong&gt;&lt;span style=&quot;font-weight:normal;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622151505_20098.png&quot; alt=&quot;&quot; /&gt;&lt;/span&gt; 
&lt;/div&gt;
&lt;/strong&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:5:"meiti";s:5:"price";s:8:"meiti_94";s:3:"com";s:7:"meiti_1";s:12:"balance_time";s:7:"meiti_1";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1466579730";}i:3;a:12:{s:2:"id";s:1:"1";s:5:"title";s:12:"暴风影音";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527123554_86434.png";s:7:"content";s:2453:"&lt;p&gt;
	&lt;span style=&quot;color:#E53333;font-size:16px;line-height:1.5;&quot;&gt;&lt;strong&gt;质量要求：真实量，不刷量，不作弊&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124427_91930.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt; &lt;/span&gt; 
&lt;/p&gt;
&lt;div&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;暴风影音软件是由北京暴风网际科技有限公司出品，从2003年开始，暴风就致力于&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;新版暴风影音为互联网用户提供最简单、便捷的互联网音视频播放解决方案。截止2012年末，暴风的工程师分析数以十万计的视频文件，掌握了超过500种视频格式的支持方案。&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;2010年1月12日暴风影音在京推出暴风影音2012版，以传统影音播放为主的暴风影音，独创&quot;SHD&quot;高清专利技术，实现了1M带宽流畅观看720P高清在线视频的先例。在随后的时间内，暴风又以1080P的更高播放画质赢得了众多用户的青睐。业内人士指出，暴风720P高清业务已在业内遥遥领先，推出1080P更是令其他同行无法企及。相对于主流的720P在线高清，暴风影音的1080P在线高清业务是专为宽带环境较好、对画质要求更为极致的用户所打造。经技术人员检测，因为1080P的高质量规格，用户需要在1.5M带宽下才可以流畅播放，但即便如此，相比承诺更高带宽可流畅播放的服务平台，暴风的技术、用户成本优势突出。&lt;br /&gt;
&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.2";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345445";}i:4;a:12:{s:2:"id";s:1:"5";s:5:"title";s:12:"酷我音乐";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613144852_32869.jpg";s:7:"content";s:3218:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;推广要求：&lt;strong&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt;真实量 &amp;nbsp;不刷量 捆绑量等都可以！评分考核.&lt;/span&gt;&lt;/strong&gt;&lt;/span&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;span style=&quot;color:#E53333;font-size:18px;&quot;&gt; &lt;/span&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;酷我音乐是中国数字音乐的交互服务品牌，是互联网领域的数字音乐服务平台，同时也是一款内容全、聆听快和界面炫的音乐聚合播放器，是国内的多种音乐资源聚合的播放软件。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;自平台成立以来，酷我音乐作为前端潮流音乐的重要推手，率先与唱片公司、版权管理机构合作探索发展，免费向广大用户提供方便流畅的在线音乐，还有免费无损音乐方便用户的试听和下载，生成了丰富的音乐流媒体生态系统。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;酷我是由前百度首席架构师雷鸣先生在2005年8月创立的。雷鸣是百度创始七剑客之一，首席架构师。他是百度搜索引擎的早期设计者和技术负责人之一。雷鸣现任酷我音乐董事长和CEO。他获得北京大学计算机科学硕士学位&lt;/span&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;和斯坦福大学商学院MBA学位，曾任北京大学计算机系学生会主席和斯坦福大学中国学生学者联合会副主席。雷鸣是国家千人计划特聘专家，北京市海聚工程特聘专家&lt;/span&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:16px;&quot;&gt;&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt;&lt;/span&gt; 
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;font-size:16px;&quot;&gt; 
&lt;div style=&quot;text-align:center;&quot;&gt;
	&lt;span style=&quot;line-height:1.5;&quot;&gt;&lt;/span&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160613/20160613145012_77346.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/div&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:3:"CPA";s:5:"price";s:7:"CPA_0.3";s:3:"com";s:5:"CPA_1";s:12:"balance_time";s:5:"CPA_3";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464346358";}}
?>