<?php
//000000000060a:2:{i:0;a:12:{s:2:"id";s:1:"7";s:5:"title";s:9:"360导航";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160612/20160612133010_81975.png";s:7:"content";s:2646:"&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&lt;span style=&quot;font-size:16px;color:#E53333;&quot;&gt;&lt;strong&gt;结算：千次IP结算！ &amp;nbsp; &lt;/strong&gt;&lt;/span&gt;&amp;nbsp;&amp;nbsp;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&amp;nbsp;&amp;nbsp;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;360导航是新一代安全上网导航，为用户提供门户、新闻、视频、游戏、小说、彩票等各种分类的优秀内容和网站入口，提供最简单便捷的上网导航服务。安全上网，从360导航开始。[1]&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 360安全网址的宗旨是方便网友们快速找到自已需要的网站，而不用去记太多复杂的网址，我的导航能让网友快速收藏喜爱的网站；同时提供多种搜索引擎入口、实用工具、快速充值、天气预报、团购导航、地方导航等特色服务。&lt;/span&gt;&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 我们打破了传统网址导航站十几年来一成不变的沉闷局面，首创了“网址+APP聚合”的模式，树立了新一代导航网站的行业标准。我们引领的APP化、个性化、地域化、工具化等特点已经成为业内其他网址站的效仿对象，引领了行业潮流。作为业内最善于创新的网站，360安全网址研发推出了大量新功能。&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:14px;color:#333333;line-height:2;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160612/20160612130357_92055.jpg&quot; alt=&quot;&quot; /&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;br /&gt;
&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;span style=&quot;font-size:14px;line-height:2;color:#333333;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:5:"meiti";s:5:"price";s:8:"meiti_70";s:3:"com";s:7:"meiti_1";s:12:"balance_time";s:7:"meiti_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464347042";}i:1;a:12:{s:2:"id";s:2:"16";s:5:"title";s:6:"好123";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622150940_71588.jpg";s:7:"content";s:3284:"&lt;p&gt;
	&lt;span style=&quot;font-size:16px;color:#E53333;background-color:#FFFFFF;&quot;&gt;&lt;strong&gt;结算：千次IP结算&lt;/strong&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;background-color:#E53333;&quot;&gt;&lt;span style=&quot;background-color:#FFFFFF;&quot;&gt;&lt;/span&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;font-size:16px;background-color:#E53333;&quot;&gt; &lt;/span&gt; 
&lt;/p&gt;
&lt;div class=&quot;para&quot; style=&quot;text-align:left;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;hao123是一款快速、功能强大的多窗口&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/8430.htm&quot;&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;上网导航&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;，它是完全免费并没有任何功能限制的上网软件。主要为上网用户提供搜索、热门网站、&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/subview/39315/7029758.htm&quot;&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;天气&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;、股票、彩票、&lt;/span&gt;&lt;a target=&quot;_blank&quot; href=&quot;http://baike.baidu.com/view/451294.htm&quot;&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;航班&lt;/span&gt;&lt;/a&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;、路况、公交等上网常用服务的实用工具，通过hao123上网导航，可以在这里阅读资讯、读小说、看视频、上微博、玩游戏、网上购物、查天气、买彩票，找新闻等，为用户提供便捷的互联网体验。&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;text-align:left;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;hao123无线，主要为用户提供搜索、热门网站、天气、股票、彩票、航班、路况、公交、酒店等上网常用服务的实用工具。通过hao123手机上网导航，您可以轻松的阅读最热门的资讯、看更多的免费小说、浏览各种视频、上微博、玩游戏、网上购物、查天气、买彩票等多种服务，为用户提供便捷的移动互联体验！&lt;/span&gt; 
&lt;/div&gt;
&lt;div class=&quot;para&quot; style=&quot;text-align:left;font-size:14px;color:#333333;font-family:arial, 宋体, sans-serif;background-color:#FFFFFF;&quot;&gt;
	&lt;span style=&quot;font-size:14px;&quot;&gt;hao123始终致力于为用户提供最简单、实用、贴心的上网导航服务。轻松上网，便捷生活，从hao123开始！&lt;/span&gt; 
&lt;/div&gt;
&lt;strong&gt; 
&lt;div style=&quot;text-align:center;&quot;&gt;
	&lt;strong&gt;&lt;span style=&quot;font-size:14px;&quot;&gt;&lt;/span&gt;&lt;/strong&gt;&lt;span style=&quot;font-weight:normal;font-size:14px;&quot;&gt;&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160622/20160622151505_20098.png&quot; alt=&quot;&quot; /&gt;&lt;/span&gt; 
&lt;/div&gt;
&lt;/strong&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:5:"meiti";s:5:"price";s:8:"meiti_94";s:3:"com";s:7:"meiti_1";s:12:"balance_time";s:7:"meiti_1";s:7:"service";s:3:"1,2";s:11:"create_time";s:10:"1466579730";}}
?>