<?php
//000000000060a:1:{i:0;a:12:{s:2:"id";s:1:"1";s:5:"title";s:12:"暴风影音";s:4:"desc";s:0:"";s:5:"image";s:79:"/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527123554_86434.png";s:7:"content";s:4104:"&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;table style=&quot;width:403px;&quot; align=&quot;center&quot; border=&quot;1&quot; bordercolor=&quot;#CCC&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; height=&quot;135&quot;&gt;
		&lt;tbody&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;推广方式&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;价格&lt;/strong&gt;&lt;strong&gt;&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					&lt;strong&gt;结算周期&lt;/strong&gt;&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPA&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					1.5&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					月结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPS&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					0.5&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					周结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td align=&quot;center&quot;&gt;
					CPC&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					0.6&lt;br /&gt;
				&lt;/td&gt;
				&lt;td align=&quot;center&quot;&gt;
					日结&lt;br /&gt;
				&lt;/td&gt;
			&lt;/tr&gt;
		&lt;/tbody&gt;
	&lt;/table&gt;
&lt;br /&gt;
&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;真实量，不刷量，不作弊&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p align=&quot;center&quot;&gt;
	&lt;img src=&quot;/Public/Plug/kindeditor-4.1.10/attached/image/20160527/20160527124427_91930.jpg&quot; alt=&quot;&quot; /&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;
&lt;p&gt;
	&lt;br /&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;/span&gt; 
&lt;/p&gt;
&lt;p&gt;
	&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt; &lt;/span&gt; 
&lt;/p&gt;
&lt;div&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;暴风影音软件是由北京暴风网际科技有限公司出品，从2003年开始，暴风就致力于&lt;/span&gt;&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;新版暴风影音为互联网用户提供最简单、便捷的互联网音视频播放解决方案。截止2012年末，暴风的工程师分析数以十万计的视频文件，掌握了超过500种视频格式的支持方案。&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;font-size:14px;color:#333333;&quot;&gt;2010年1月12日暴风影音在京推出暴风影音2012版，以传统影音播放为主的暴风影音，独创&quot;SHD&quot;高清专利技术，实现了1M带宽流畅观看720P高清在线视频的先例。在随后的时间内，暴风又以1080P的更高播放画质赢得了众多用户的青睐。业内人士指出，暴风720P高清业务已在业内遥遥领先，推出1080P更是令其他同行无法企及。相对于主流的720P在线高清，暴风影音的1080P在线高清业务是专为宽带环境较好、对画质要求更为极致的用户所打造。经技术人员检测，因为1080P的高质量规格，用户需要在1.5M带宽下才可以流畅播放，但即便如此，相比承诺更高带宽可流畅播放的服务平台，暴风的技术、用户成本优势突出。&lt;br /&gt;
&lt;/span&gt; 
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
	&lt;p&gt;
		&lt;br /&gt;
	&lt;/p&gt;
&lt;/div&gt;
&lt;span style=&quot;color:#333333;font-size:14px;line-height:1.5;&quot;&gt;&lt;br /&gt;
&lt;/span&gt; 
&lt;p&gt;
	&lt;br /&gt;
&lt;/p&gt;";s:4:"type";s:1:"1";s:4:"attr";s:11:"CPA,CPS,CPC";s:5:"price";s:23:"CPA_1.5,CPS_0.5,CPC_0.6";s:3:"com";s:17:"CPA_1,CPS_0,CPC_0";s:12:"balance_time";s:17:"CPA_3,CPS_2,CPC_1";s:7:"service";s:1:"1";s:11:"create_time";s:10:"1464345445";}}
?>